# Generated by Django 3.0.6 on 2020-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200610_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
