# Generated by Django 3.0.6 on 2020-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200610_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, upload_to='post_image')),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
