# Generated by Django 3.0.6 on 2020-06-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200611_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image/')),
                ('cour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.Cour')),
            ],
        ),
    ]
