# Generated by Django 3.0.6 on 2020-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200613_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='courimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
