# Generated by Django 3.0.6 on 2020-06-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_remove_cour_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='created_on',
        ),
    ]
