# Generated by Django 3.0.6 on 2020-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200622_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
